---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  namespace: "prometheus-op"
  annotations: {}
  name: "prometheus-operator"
  labels:
    app: "prometheus-operator"
    app.kubernetes.io/name: "prometheus"
    release: "prometheus"
    heritage: "Tiller"
    chart: "prometheus-operator-9.3.0"
    app.kubernetes.io/component: "deployment.prometheus-operator"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: "prometheus-operator"
      release: "prometheus"
      app.kubernetes.io/component: "deployment.prometheus-operator"
    matchExpressions: []
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations: {}
      labels:
        app: "prometheus-operator"
        app.kubernetes.io/name: "prometheus-allinone"
        release: "prometheus"
        heritage: "Tiller"
        chart: "prometheus-operator-9.3.0"
        app.kubernetes.io/component: "deployment.prometheus-operator"
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      serviceAccountName: "prometheus-operator"
      containers:
      - name: "prometheus"
        image: "quay.io/coreos/prometheus-operator:v0.42.1"
        command: []
        args:
        - "--kubelet-service=kube-system/prometheus-kubelet"
        - "--logtostderr=true"
        - "--localhost=127.0.0.1"
        - "--prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.42.1"
        - "--config-reloader-image=docker.io/jimmidyson/configmap-reload:v0.3.0"
        - "--config-reloader-cpu=100m"
        - "--config-reloader-memory=25Mi"
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: "http"
          containerPort: 8080
          protocol: "TCP"
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        resources:
          limits: {}
          requests: {}
      securityContext:
        runAsUser: 65534
        runAsNonRoot: true
        fsGroup: 65534
        runAsGroup: 65534
        supplementalGroups: []
