---
metadata:
  namespace: "prometheus-op"
  name: "prometheus-prometheus"
  labels:
    app: "prometheus-prometheus"
    release: "prometheus"
    heritage: "Tiller"
    chart: "prometheus-operator-9.3.0"
apiVersion: "monitoring.coreos.com/v1"
kind: "Prometheus"
spec:
  externalUrl: "http://prometheus-prometheus.prometheus-op:9090"
  paused: false
  ruleNamespaceSelector: {}
  replicas: 1
  serviceAccountName: "prometheus-prometheus"
  ruleSelector:
    matchLabels:
      app: "prometheus"
      release: "prometheus"
  baseImage: "quay.io/prometheus/prometheus"
  listenLocal: false
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
  portName: "web"
  version: "v2.18.2"
  podMonitorSelector:
    matchLabels:
      release: "prometheus"
  alerting:
    alertmanagers:
    - apiVersion: "v2"
      port: "web"
      namespace: "prometheus-op"
      name: "prometheus-alertmanager"
      pathPrefix: "/"
  serviceMonitorNamespaceSelector: {}
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  logFormat: "logfmt"
  logLevel: "info"
  enableAdminAPI: false
  routePrefix: "/"
  podMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: "prometheus"
  tolerations:
  - effect: NoSchedule
    operator: Exists
  retention: "10d"
