---
apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "prometheus-op"
  annotations:
    prometheus.io/scrape: "true"
  name: "node-exporter"
  labels:
    app: "prometheus-node-exporter"
    jobLabel: "node-exporter"
    app.kubernetes.io/name: "prometheus"
    release: "prometheus"
    heritage: "Tiller"
    chart: "prometheus-node-exporter-1.10.0"
    app.kubernetes.io/component: "daemonset.node-exporter"
spec:
  clusterIP: "None"
  externalIPs: []
  loadBalancerSourceRanges: []
  type: "ClusterIP"
  selector:
    app: "prometheus-node-exporter"
    release: "prometheus"
    app.kubernetes.io/component: "daemonset.node-exporter"
  ports:
  - name: "metrics"
    port: 9100
    protocol: "TCP"
    targetPort: 9100
