apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-velero
    release: prometheus
  name: prometheus-velero
  namespace: velero
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app.kubernetes.io/component: deployment.velero
  sessionAffinity: None
  type: ClusterIP
