---
apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "kube-system"
  annotations: {}
  name: "prometheus-coredns"
  labels:
    app: "prometheus-coredns"
    jobLabel: "coredns"
    app.kubernetes.io/name: "prometheus"
    release: "prometheus"
    heritage: "Tiller"
    chart: "prometheus-operator-9.3.0"
spec:
  clusterIP: "None"
  externalIPs: []
  loadBalancerSourceRanges: []
  type: "ClusterIP"
  selector:
    k8s-app: "kube-dns"
  ports:
  - name: "http-metrics"
    port: 9153
    protocol: "TCP"
    targetPort: 9153
