---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  namespace: "prometheus-op"
  annotations: {}
  name: "node-exporter"
  labels:
    app: "prometheus-node-exporter"
    heritage: "Tiller"
    app.kubernetes.io/name: "prometheus"
    chart: "prometheus-node-exporter-1.10.0"
    release: "prometheus"
