---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  namespace: "prometheus-op"
  annotations: {}
  name: "kube-state-metrics"
  labels:
    helm.sh/chart: "kube-state-metrics-2.8.10"
    app.kubernetes.io/managed-by: "Tiller"
    app.kubernetes.io/name: "kube-state-metrics"
    app.kubernetes.io/instance: "prometheus"
