---
apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "prometheus-op"
  annotations: {}
  name: "prometheus-prometheus"
  labels:
    app: "prometheus-prometheus"
    self-monitor: "true"
    app.kubernetes.io/name: "prometheus"
    release: "prometheus"
    heritage: "Tiller"
    chart: "prometheus-operator-9.3.0"
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  type: "ClusterIP"
  selector:
    app: "prometheus"
    prometheus: "prometheus-prometheus"
  ports:
  - name: "web"
    port: 9090
    targetPort: 9090
