---
apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "kube-system"
  annotations: {}
  name: "prometheus-kube-controller-manager"
  labels:
    app: "prometheus-kube-controller-manager"
    jobLabel: "kube-controller-manager"
    app.kubernetes.io/name: "prometheus"
    release: "prometheus"
    heritage: "Tiller"
    chart: "prometheus-operator-9.3.0"
spec:
  clusterIP: "None"
  externalIPs: []
  loadBalancerSourceRanges: []
  type: "ClusterIP"
  selector:
    component: "kube-controller-manager"
  ports:
  - name: "http-metrics"
    port: 10252
    protocol: "TCP"
    targetPort: 10252
