---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  namespace: "prometheus-op"
  annotations: {}
  name: "prometheus-operator"
  labels:
    app: "prometheus-operator"
    heritage: "Tiller"
    app.kubernetes.io/name: "prometheus"
    chart: "prometheus-operator-9.3.0"
    release: "prometheus"
