---
metadata:
  namespace: "prometheus-op"
  name: "prometheus-node-exporter"
  labels:
    app: "prometheus-node-exporter"
    release: "prometheus"
    heritage: "Tiller"
    chart: "prometheus-operator-9.3.0"
apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
spec:
  jobLabel: "jobLabel"
  endpoints:
  - port: "metrics"
  selector:
    matchLabels:
      app: "prometheus-node-exporter"
      release: "prometheus"
