---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  name: "prometheus-blackbox-exporter"
  labels:
    helm.sh/chart: "prometheus-blackbox-exporter-5.8.1"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "prometheus-blackbox-exporter"
    app.kubernetes.io/version: "0.20.0"
spec:
  ipFamilies:
  - "IPv4"
  ipFamilyPolicy: "SingleStack"
  internalTrafficPolicy: "Cluster"
  externalIPs: []
  loadBalancerSourceRanges: []
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "prometheus-blackbox-exporter"
    app.kubernetes.io/instance: "bb-exp"
  ports:
  - name: "http"
    port: 9115
    protocol: "TCP"
    targetPort: "http"
