---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations: {}
  name: "prometheus-blackbox-exporter"
  labels:
    helm.sh/chart: "prometheus-blackbox-exporter-5.8.1"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "prometheus-blackbox-exporter"
    app.kubernetes.io/instance: "bb-exp"
    app.kubernetes.io/version: "0.20.0"
