---
apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "prometheus-op"
  annotations:
    prometheus.io/scrape: "true"
  name: "kube-state-metrics"
  labels:
    helm.sh/chart: "kube-state-metrics-2.8.10"
    app.kubernetes.io/managed-by: "Tiller"
    app.kubernetes.io/name: "kube-state-metrics"
    app.kubernetes.io/instance: "prometheus"
    app.kubernetes.io/component: "deployment.kube-state-metrics"
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "kube-state-metrics"
    app.kubernetes.io/instance: "prometheus"
    app.kubernetes.io/component: "deployment.kube-state-metrics"
  ports:
  - name: "http"
    port: 8080
    protocol: "TCP"
    targetPort: 8080
